name:                binary-analysis
version:             0.1.0.0
license:             LicenseRef-Proprietary
author:              "drone"
maintainer:          "drone@kududyn.com"
copyright:           "2020 Kudu Dynamics"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Common data types and utilities for binary analysis

default-extensions:
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- generic-deriving
- hashable
- lens
- text
- unordered-containers
- smallcheck

library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -j
  - -O2
  source-dirs: src
  exposed-modules:
  - Data.BinaryAnalysis

tests:
  binary-analysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary-analysis
